# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- openrgb --startminimized --profile "RED"
exec-once = bash ~/.config/hypr/fix-audio.sh
exec-once = snixembed --fork
