general {
    lock_cmd = omarchy-system-lock                         # lock screen and 1password
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock    # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && omarchy-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
    ignore-dbus-inhibit = true                             # ignore D-Bus idle inhibit (e.g. org.freedesktop.ScreenSaver)
    ignore_wayland_inhibit = true                          # ignore Wayland protocol idle inhibit (e.g. Chrome/Firefox playing media)
    ignore_systemd_inhibit = true                          # ignore systemd idle inhibit
}

# Turn off monitors after 2 hours of inactivity
listener {
    timeout = 7200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
